services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app_net
  
  backend:
    build:
      context: ./backend
      target: dev
    user: "0:0"
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app_net
  
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- -- host 0.0.0.0"
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - app_net
  
  llm:
    build:
      context: ./llm
    ports:
      - "8000:8000"
    volumes:
      - ./llm:/app
    env_file:
      - .env
    networks:
      - app_net

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${DOZZLE_PORT}:8080"
    networks:
      - app_net
    environment:
      - DOZZLE_LEVEL=${DOZZLE_LEVEL}

volumes:
  db_data:

networks:
  app_net:
    driver: bridge

